mysites/mysites/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('pollssite.urls')),
    path('admin/', admin.site.urls),
]

mysites/pollssite/urls.py
from django.urls import path

from . import views

app_name = 'polls3'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detailofques'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='res'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

mysites/pollssite/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() - datetime.timedelta(days=1) <=self.pub_date <= timezone.now()
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'published recently'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

# lallalalalla

mysites/pollssite/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'pollssite/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
        # print(question_list)
        latest_question_list = list()
        for question in question_list:
            choice_count = question.choice_set.count()
            # print("_________________")
            # print(choice_count)
            if choice_count != 0:
                latest_question_list.append(question)

        # print(latest_question_list)
        return latest_question_list


# def index(request):
#     print(request)
#     print('___________')
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list, }
#     return render(request, 'pollssite/index.html', context)  # finally return HttpResponse

class DetailView(generic.DetailView):
    model = Question
    template_name = 'pollssite/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     mapping_variables = {'question': question, }
#     return render(request, 'pollssite/detail.html', mapping_variables)


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'pollssite/res.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     mapping_variables = {'question': question, }
#     return render(request, 'pollssite/res.html', mapping_variables)
#

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choiceID'])
    except(KeyError, Choice.DoesNotExist):
        mapping = {'question': question, 'error_message': "You didn't select a choice to vote"}
        return render(request, 'pollssite/detail.html', mapping)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls3:res', args=(question_id,)))

mysites/pollssite/templates/pollssite/detail.html
<h1>{{ question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls3:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choiceID" id="choice{{forloop.counter}}" value="{{choice.id}}">
    <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysites/pollssite/templates/pollssite/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pollssite/style.css' %}">


<h2> Poll app 3</h2>
<h1> Latest question</h1>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li> <a href="{% url 'polls3:detailofques' question.id %}">{{ question.question_text }} </a></li>
     {% endfor %}
    </ul>
{% else %}
    <p>No polls are available =)))) </p>
{% endif %}

mysites/pollssite/templates/pollssite/res.html
<h1>{{ question }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}} -- {{ choice.votes}} vote {{choice.votes|pluralize }} </li>
{% endfor %}
</ul>

<a href="{% url 'polls3:detailofques' question.id %}"> Vote again?</a>